apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonschema-validation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsonschema-validation-webhook
  template:
    metadata:
      labels:
        app: jsonschema-validation-webhook
    spec:
      containers:
      - name: webhook
        image: cuttingedge1109/jsonschema-validation-webhook:latest
        ports:
        - containerPort: 443
