apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
      - name: webhook
        image: cuttingedge1109/validation-webhook:latest
        ports:
        - containerPort: 443
