---
apiVersion: v1
kind: Service
metadata:
  name: jsonschema-validation-webhook
  namespace: default
  labels:
    app: jsonschema-validation-webhook
spec:
  ports:
  - name: webhook
    port: 443
  selector:
    app: jsonschema-validation-webhook
